package com.adobe.epubcheck.api;

public enum ReportEnum {
	// EpubCheck.java
	WARN_EXT_USE_LOWERCASE,
	WARN_EXT_UNCOMMON,
	
	// DTBookHandler.java
	WARN_URI_SCHEMA_NOT_REGISTERED,
	
	// CSSChecker.java
	WARN_CSS_EXCEPTION,
	WARN_CSS_FIXED_POSITION,
	WARN_CSS_PROPERTY_NOT_ALLOWED,
	WARN_CSS_NON_STANDARD_FONT_TYPE,
	
	// EpubCheck.java / OPSHandler30.java
	ERR_HEADER_READ_ERROR,
	ERR_HEADER_ZIP_CORRUPT,
	ERR_MIMETYPE_CONFLICT,
	ERR_MIMETYPE_MISSING,
	ERR_MIMETYPE_INCORRECT,
	ERR_MIMETYPE_TOO_LONG,
	
	// BitmapChecker.java
	ERR_MIMETYPE_INCORRECT_FOR_IMAGE,
	ERR_IMAGE_FILE_MISSING,
	ERR_IMAGE_FILE_TOO_SHORT,
	
	// CSSChecker.java
	ERR_TEXT_ENCODING_UNSUPPORTED,
	
	// NavChecker.java
	ERR_NAV_FILE_UNSUPPORTED,
	
	// NCXChecker.java
	ERR_NCX_BAD_UID,
	ERR_NCX_SCHEMATRON_TEST_FAILURE,
	
	// OCFChecker.java
	WARN_EPUB_VERSION_NOT_FOUND,
	WARN_EPUB_VERSION_MISMATCH,
	WARN_EMPTY_DIRECTORY,
	WARN_OCF_MULTIPLE_OPS,
	ERR_OCF_NO_OEBPS_PACKAGE_FILE,
	ERR_OPF_HAS_NO_ENTRY_FOR_FILE,
	ERR_ROOTPATH_NOT_AN_OPF_FILE,
	
	// OPFChecker30.java
	ERR_OPF_FALLBACK_MISSING,
	
	// OCFFilenameChecker.java
	ERR_FILENAME_CONTAINS_DISSALLOWED_CHARS,
	ERR_FILENAME_ENDS_WITH_DOT,
	WARN_FILENAME_CONTAINS_SPACES,
	WARN_FILENAME_NOT_ASCII,
	
	// OverlayHandler.java
	ERR_XML_UNDECLARED_PREFIX,
	ERR_AUDIO_NON_STANDARD_TYPE,
	
	// XMLParser.java
	ERR_XML_EXCEPTION,
	ERR_DOCTYPE_IRREGULAR,
	ERR_DOCTYPE_EXTERNAL_DTD,
	ERR_ENTITY_EXTERNAL,
	ERR_ENTITY_UNDECLARED,
	
	// General
	ERR_EXCEPTION,
	ERR_FILE_DUPLICATE_IN_ZIP,
	ERR_FILE_ENCRYPTED,
	ERR_FILE_MISSING,
	ERR_IO,
	ERR_NULL_REFERENCE,
	ERR_RESOURCE_ENCRYPTED,
	ERR_RESOURCE_MISSING,
	
	// 
	NULL
	
}
